# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-30 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161229_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
