# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20161230_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category_name', models.CharField(max_length=10, verbose_name='Category')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='salepost',
            name='poster',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_name',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='core.Category'),
        ),
        migrations.DeleteModel(
            name='SalePost',
        ),
    ]
